### ISSUE TITLE
get_object() got an unexpected keyword argument 'RequestPayer'

### ISSUE THREAD

**Issue by philvarner** [matthewhanson/boto3-utils#22]
With 

```
boto3==1.24.59
botocore==1.27.59
boto3-utils==0.4.0
```

This exception happens when trying to use requester pays:

```
ERROR    task.py:250 get_object() got an unexpected keyword argument 'RequestPayer'
Traceback (most recent call last):
  File ".venv/lib/python3.9/site-packages/stactask/task.py", line 242, in handler
    items = task.process(**task.parameters)
  File "task.py", line 262, in process
    v0_json = s3_client.read_json(v0_url)
  File ".venv/lib/python3.9/site-packages/boto3utils/s3.py", line 259, in read_json
    return json.loads(self.read(url))
  File ".venv/lib/python3.9/site-packages/boto3utils/s3.py", line 251, in read
    response = self.get_object(parts['bucket'], parts['key'], **kwargs)
TypeError: get_object() got an unexpected keyword argument 'RequestPayer'
```

from code:

```
        kwargs = {}
        if self.requester_pays:
            kwargs["RequestPayer"] = "requester"
        response = self.get_object(parts['bucket'], parts['key'], **kwargs)
```

I believe it's expecting an `ExtraArgs` parameter instead of `RequestPayer` directly, but I've been unable to find exactly where that's documented and for which version of boto3.

**Comment by matthewhanson** [comment]
I see, looks like a problem with just the read function because it's passing in requester pays to s3.get_object, but s3.get_object is just getting the requester pays attribute for the whole session, so the read function should not check for it and try to pass it in.

Temp workaround would be to just download the file then read it from disk.
